### ISSUE TITLE
Error 4018: Combining traits no longer works with moonc v0.1.20250304+fdfcb3f1f

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#1743]
In this PR: https://github.com/gmlewis/moonbit-flate/pull/2
I show how the combination of two traits from a different (external) package:

* `@io.Reader`
* `@io.ByteReader`

into a single trait:

```moonbit
///| The actual read interface needed by [Decompressor::new].
pub(open) trait Reader {
  // @io.Reader
  read(Self, Slice[Byte]) -> (Int, IOError?)
  // @io.ByteReader
  read_byte(Self) -> (Byte, IOError?)
}
```

Now causes the error: `Type @io.Buffer does not implement trait @flate.Reader: method read is missing(4018)`
even though the method is here: https://github.com/gmlewis/moonbit-io/blob/620780432bfb9ad985c1e93bb27fd3bc83584cf5/buffer.mbt#L59
and the trait is here: https://github.com/gmlewis/moonbit-io/blob/620780432bfb9ad985c1e93bb27fd3bc83584cf5/io.mbt#L88-L90

It is not obvious to me how to fix this new error using the `impl` syntax since the trait is external to this package (which I thought was one of the really nice features of traits).

Changing `Slice[Byte]` to `@io.Slice[Byte]` and `IOError` to `@io.IOError` above doesn't seem to make a difference.

Any help to make this work again would be greatly appreciated, as it was working before the latest compiler update.

**Comment by Yu-zh** [comment]
<img width="833" alt="Image" src="https://github.com/user-attachments/assets/e00cfde1-f257-44bf-a8c4-43d0c1912d01" />

Try adding `pub` to these `impl`s. It works on my machine.

**Comment by gmlewis** [comment]
Oh, wow, stupid mistake.  Thank you, @Yu-zh !
Sorry for the noise!

**Comment by gmlewis** [comment]
@Yu-zh - I'm still seeing this after the change:

```
glenn@glenn-MacM2Pro ~/src/github.com/gmlewis/moonbit-07-flate (broken-traits) $ ./update.sh
+ moon update
failed to update registry, re-cloning
Registry index re-cloned successfully
+ moon install
+ rm -rf target
+ moon fmt
+ moon info
failed: moonc check /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/deflate_test.mbt /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/deflate-fast_test.mbt -o /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/target/wasm-gc/release/check/flate.blackbox_test.mi -pkg gmlewis/flate_blackbox_test -std-path /Users/glenn/.moon/lib/core/target/wasm-gc/release/bundle -i /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/target/wasm-gc/release/check/flate.mi:flate -i /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/target/wasm-gc/release/check/.mooncakes/gmlewis/io/io.mi:io -pkg-sources gmlewis/flate_blackbox_test:/Users/glenn/src/github.com/gmlewis/moonbit-07-flate -target wasm-gc -blackbox-test
/Users/glenn/src/github.com/gmlewis/moonbit-07-flate/deflate-fast_test.mbt:82:53-82:56 [E1045] Warning: Type @gmlewis/io.Buffer implements trait @gmlewis/flate.Reader with regular methods read_byte, this behavior is deprecated and will be removed in the future, write explicit `impl` instead.
/Users/glenn/src/github.com/gmlewis/moonbit-07-flate/deflate-fast_test.mbt:82:53-82:56 [E4018] Type @gmlewis/io.Buffer does not implement trait @gmlewis/flate.Reader: method read is missing
error: failed to run moon info for target WasmGC

Caused by:
    moon check failed
```

Any ideas?

**Comment by gmlewis** [comment]
Now, after updating the `@io.Buffer` with a missing `impl`, the error message changed slightly, but still basically the same:

```
glenn@glenn-MacM2Pro ~/src/github.com/gmlewis/moonbit-07-flate (broken-traits) $ ./update.sh
+ moon update
failed to update registry, re-cloning
Registry index re-cloned successfully
+ moon install
+ rm -rf target
+ moon fmt
+ moon info
failed: moonc check /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/deflate_test.mbt /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/deflate-fast_test.mbt -o /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/target/wasm-gc/release/check/flate.blackbox_test.mi -pkg gmlewis/flate_blackbox_test -std-path /Users/glenn/.moon/lib/core/target/wasm-gc/release/bundle -i /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/target/wasm-gc/release/check/flate.mi:flate -i /Users/glenn/src/github.com/gmlewis/moonbit-07-flate/target/wasm-gc/release/check/.mooncakes/gmlewis/io/io.mi:io -pkg-sources gmlewis/flate_blackbox_test:/Users/glenn/src/github.com/gmlewis/moonbit-07-flate -target wasm-gc -blackbox-test
/Users/glenn/src/github.com/gmlewis/moonbit-07-flate/deflate-fast_test.mbt:82:53-82:56 [E4018] Type @gmlewis/io.Buffer does not implement trait @gmlewis/flate.Reader:
  - method read is missing
  - method read_byte is missing
error: failed to run moon info for target WasmGC

Caused by:
    moon check failed
```

**Comment by peter-jerry-ye** [comment]
So here's the thing:

The original way of implementing a trait is **structural**, meaning that if a type has a method (`T::f` of `f(self : T)`), then it fulfills **any** trait that requires that method.

The new way of implementing a trait is **nominal**, meaning that if a type implements a method of a specific trait, then it fulfills **only** that trait.

The former is the golang's way, and the latter is the rust's way. We are going to switch to the latter one because of some issues brought by the structural trait (complicated implementation in the compiler, difficult to find out all the implemented traits, etc.)

So, in your case, you will need to add another implementation (by using `impl`) for the combination of (`@io.Buffer`, `@flate.Reader`). Note that such implementation can only take place either in the package of the type or the package of the trait.

**Comment by gmlewis** [comment]
Thanks again, @peter-jerry-ye!
And thank you for fixing the problem in my repo!

**Comment by gmlewis** [comment]
@peter-jerry-ye - how would I satisfy two traits with a single method?

For example, I have these two traits that have overlap, but serve different purposes:

```moonbit
pub(open) trait Reader {
  read(Self, Slice[Byte]) -> (Int, IOError?)
}

pub(open) trait ReadCloser {
  read(Self, Slice[Byte]) -> (Int, IOError?)
  close(Self) -> IOError?
}
```

Now in an external repo, I have a `@gzip.Reader` struct that satisfies _BOTH_ traits, but now I must explicitly declare both, however there is only one `read` method.

How do I declare that `read` satisfies both?

Here is my example I'm trying to resolve: https://github.com/gmlewis/moonbit-gzip/pull/1/files

It gives me this error: 

![Image](https://github.com/user-attachments/assets/a0bc37c2-2a67-4fda-b2d2-5aa7ff9c83d2)

And here is the definition:

```moonbit
pub impl @io.ReadCloser for Reader with read(self, p) { ... }
```

**Comment by gmlewis** [comment]
Oh!  I think you already answered this question months ago, here:
https://github.com/moonbitlang/moonbit-docs/issues/342#issuecomment-2526777849
Thank you, @peter-jerry-ye!
